name: jazzx_app
description: A music practice app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  flutter_sound: ^9.2.13
 
 # Firebase stack (compatible with each other and web-safe)
  firebase_core: ^3.13.1
  firebase_auth_web: ^5.14.3
  firebase_core_web: ^2.23.0
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6

  # YouTube Player compatible with Firebase
  youtube_player_iframe: ^5.2.1

  # Other plugins (update as needed)
  provider: ^6.1.1
  receive_sharing_intent: ^1.6.6
  file_picker: ^10.1.9
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  audioplayers: ^6.4.0
  # soundpool: ^2.4.1 # REMOVED - Discontinued
  logging: ^1.3.0
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0 
  webview_flutter: ^4.13.0  
  http: ^1.3.0  # Upgraded for google_fonts compatibility
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.4+4  
  googleapis_auth: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  logger: ^2.5.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^7.6.4
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  clock: ^1.1.1
  package_info_plus: ^4.2.0

  # js: ^0.6.7
  # pitch_detector_dart: ^0.0.7
  # web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/jazzx_logo.svg
    - assets/icons/
    - assets/sounds/

environment:
  sdk: ^3.7.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/jazzx_logo.png"
