// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrvSZDV7eV1ENrm4KGeFCULjkM-KdkpkM',
    appId: '1:824026860782:web:73e11e19366cf48377f7ff',
    messagingSenderId: '824026860782',
    projectId: 'jazzx-97daf',
    authDomain: 'jazzx-97daf.firebaseapp.com',
    databaseURL: 'https://jazzx-97daf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jazzx-97daf.firebasestorage.app',
    measurementId: 'G-PD7MENNSHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHlBA5qGga8dtw-id9-UMZwpeTPhiiJ8',
    appId: '1:824026860782:android:d3dd15914d9e252f77f7ff',
    messagingSenderId: '824026860782',
    projectId: 'jazzx-97daf',
    databaseURL: 'https://jazzx-97daf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jazzx-97daf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeYZ3JKvU3uUAmL1Zxd53kgNWoIppyPBE',
    appId: '1:824026860782:ios:efb360c68d3cfe8a77f7ff',
    messagingSenderId: '824026860782',
    projectId: 'jazzx-97daf',
    databaseURL: 'https://jazzx-97daf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jazzx-97daf.firebasestorage.app',
    androidClientId: '824026860782-99490k01d13k766bdorakqgqub1neltl.apps.googleusercontent.com',
    iosClientId: '824026860782-41tljlcffs0sirr8nf4ue3k4bof1d0lt.apps.googleusercontent.com',
    iosBundleId: 'com.innubili.jazzx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeYZ3JKvU3uUAmL1Zxd53kgNWoIppyPBE',
    appId: '1:824026860782:ios:54802af7318812bc77f7ff',
    messagingSenderId: '824026860782',
    projectId: 'jazzx-97daf',
    databaseURL: 'https://jazzx-97daf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jazzx-97daf.firebasestorage.app',
    androidClientId: '824026860782-99490k01d13k766bdorakqgqub1neltl.apps.googleusercontent.com',
    iosClientId: '824026860782-lbppmsb806371q8c93alucrum67mfm6q.apps.googleusercontent.com',
    iosBundleId: 'com.innubili.jazzxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrvSZDV7eV1ENrm4KGeFCULjkM-KdkpkM',
    appId: '1:824026860782:web:3a39deba536ab3a777f7ff',
    messagingSenderId: '824026860782',
    projectId: 'jazzx-97daf',
    authDomain: 'jazzx-97daf.firebaseapp.com',
    databaseURL:
        'https://jazzx-97daf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jazzx-97daf.appspot.com',
    measurementId: 'G-5NQLCWY20X',
  );
}